# Generated by Django 5.1.4 on 2025-01-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contactNum', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('is_Admin', models.BooleanField(default=False)),
            ],
        ),
    ]
