# Generated by Django 5.1.4 on 2025-01-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_rename_is_admin_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_superUser',
            new_name='is_staff',
        ),
    ]
