# Generated by Django 5.1.4 on 2025-01-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_passwordresetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contactNum',
            field=models.IntegerField(),
        ),
    ]
