# Generated by Django 5.1.4 on 2025-01-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_customuser_contactnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
