# Generated by Django 5.1.4 on 2025-01-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_alter_option_question_alter_response_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multpile choice'), ('SA', 'Short Answer')], max_length=5),
        ),
    ]
