# Generated by Django 5.1.4 on 2025-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0006_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
