# Generated by Django 5.1.4 on 2025-01-28 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0008_rename_response_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Survey.survey'),
            preserve_default=False,
        ),
    ]
